# -*- coding: utf-8 -*-
"""logistics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vh9bWET4WEkPEfVHYN6CL77Zmb8GcypV
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

df_log=pd.read_csv("/content/Delivery_Logistics.csv")
df_log.head()

df_log.info()

df_log.shape

for col in df_log.columns:
  if df_log[col].dtype==object:
    print(f"col name is {col}",end="\n")
    print("-"*100)
    # print(df[col].unique().count())
    print(df_log[col].value_counts())
    print("-"*100,end="\n\n")

city_coords = {
    'north': [
        ('Delhi', 28.6139, 77.2090),
        ('Lucknow', 26.8467, 80.9462),
        ('Jaipur', 26.9124, 75.7873),
        ('Chandigarh', 30.7333, 76.7794),
        ('Agra', 27.1767, 78.0081),
    ],
    'south': [
        ('Chennai', 13.0827, 80.2707),
        ('Bangalore', 12.9716, 77.5946),
        ('Hyderabad', 17.3850, 78.4867),
        ('Kochi', 9.9312, 76.2673),
        ('Coimbatore', 11.0168, 76.9558),
    ],
    'east': [
        ('Kolkata', 22.5726, 88.3639),
        ('Bhubaneswar', 20.2961, 85.8245),
        ('Patna', 25.5941, 85.1376),
        ('Guwahati', 26.1445, 91.7362),
        ('Ranchi', 23.3441, 85.3096),
    ],
    'west': [
        ('Mumbai', 19.0760, 72.8777),
        ('Pune', 18.5204, 73.8567),
        ('Ahmedabad', 23.0225, 72.5714),
        ('Surat', 21.1702, 72.8311),
        ('Nagpur', 21.1458, 79.0882),
    ],
    'central': [
        ('Bhopal', 23.2599, 77.4126),
        ('Indore', 22.7196, 75.8577),
        ('Jabalpur', 23.1815, 79.9864),
        ('Gwalior', 26.2183, 78.1828),
        ('Raipur', 21.2514, 81.6296),
    ],
}

def assign_city(region):
    cities = city_coords.get(region, [('Unknown', 0.0, 0.0)])
    choice = cities[np.random.randint(len(cities))]
    return pd.Series({
        'city': choice[0],
        'latitude': choice[1],
        'longitude': choice[2]
    })

df_log[['city', 'latitude', 'longitude']] = df_log['region'].apply(assign_city)

df_log.head()

df_log.info()

# dashboard kpis
df_log['delivery_mode'].value_counts()

total_deliveries=df_log.shape[0]
print(f"total deliveries what we have in present or completed {total_deliveries}")

print(df_log['delivery_status'].value_counts())

print("status")
for key,value in df_log['delivery_status'].value_counts().items():
  print(f"{key}:{value}")

df_log['delayed'].value_counts()

delivery_rate=(df_log[df_log['delayed']=='no'].shape[0]/df_log.shape[0])*100
print(f"no delay delivery rate is {delivery_rate}")
print(f"delay in delivery rate is {100-delivery_rate}")

df_log.isnull().sum()

df_log['delivery_cost'].sum()

x=(df_log['delivery_rating'].sum()/df_log.shape[0])
print(x)

df_log.groupby('city')

division=df_log.groupby('city')
for group,data in division:
  print(f"city name: {group}")
  print("-"*100)
  print("total deliveries:",data.size)
  print("yes delivery rate",(data[data['delayed']=='no'].size/data.size)*100)
  print("no delivery rate",(data[data['delayed']=='yes'].size/data.size)*100)
  print("average rating ",data['delivery_rating'].mean())
  print("total cost operated",data['delivery_cost'].sum())
  print("-"*100,end="\n\n")



date_range = pd.date_range(
    start='2024-05-30',
    end='2027-06-30',
    freq='D'
)

df_log['order_date'] = np.random.choice(
    date_range,
    size=len(df_log)
)



expected_days = np.random.randint(
    1,
    6,
    size=len(df_log)
)

df_log['expected_delivery_date'] = (
    df_log['order_date'] +
    pd.to_timedelta(expected_days, unit='D')
)



df_log['delivery_date'] = df_log['expected_delivery_date']


delay_mask = df_log['delayed'].str.lower() == 'yes'

additional_delay = np.random.randint(
    1,
    4,
    size=delay_mask.sum()
)

df_log.loc[
    delay_mask,
    'delivery_date'
] = (
    df_log.loc[
        delay_mask,
        'expected_delivery_date'
    ] +
    pd.to_timedelta(
        additional_delay,
        unit='D'
    )
)

df_log.info()

df_log.drop(columns=['delivery_time_hours','expected_time_hours'],inplace=True)

df_log.info()
df_log[df_log['delayed']=='yes'].head()

df_log[df_log['order_date']==pd.to_datetime('2025-06-30')].size

df_log['package_type'].value_counts()

daily = (
    df_log.groupby('order_date')
      .size()
      .reset_index(name='daily_shipment_count')
      .sort_values('order_date',ascending=True)
      .set_index('order_date')
)

print(daily.shape)
print(daily.head(5))

df_log.groupby('order_date').size()

# daily=df_log.groupby('order_date')
# df_log['number_of_shipments']=df_log['order_date'].apply(lambda x:daily.get_group(x).shape[0])



df_log[df_log['order_date']==pd.to_datetime('2025-06-30')].head()

df_log.head()

df_log.isnull().sum()

df_log['month'] = df_log['order_date'].dt.month


df_log['day_of_week'] = df_log['order_date'].dt.dayofweek


df_log['week_of_year'] = df_log['order_date'].dt.isocalendar().week.astype(int)

df_log['quarter'] = df_log['order_date'].dt.quarter


df_log['is_weekend'] = (
    df_log['order_date'].dt.dayofweek >= 5
).astype(int)

df_log['is_month_start'] = (
    df_log['order_date'].dt.is_month_start
).astype(int)

df_log['is_month_end'] = (
    df_log['order_date'].dt.is_month_end
).astype(int)

# df_log.info()
df_log.head()

df_model_1=df_log[['order_date','month','week_of_year','quarter','is_weekend','is_month_start','is_month_end']].copy()
df_model_1.head()

df_model_1.shape
# df_model_1.shape
# df_model_1.drop_duplicates(keep='first',inplace=True)
# df_model_1.shape
daily=df_model_1.groupby('order_date')
df_model_1['number_of_shipments']=df_model_1['order_date'].apply(lambda x:daily.get_group(x).shape[0])

df_model_1.drop_duplicates(keep='first',inplace=True)
df_model_1.shape

df_model_1 = df_model_1.sort_values('order_date').reset_index(drop=True)
target = df_model_1['number_of_shipments']

df_model_1['lag_1']  = target.shift(1)    # yesterday's count
df_model_1['lag_7']  = target.shift(7)    # same day last week
df_model_1['lag_14'] = target.shift(14)   # same day 2 weeks ago
df_model_1['lag_28'] = target.shift(28)   # same day 4 weeks ago

print(df_model_1[['order_date','number_of_shipments','lag_1','lag_7','lag_14','lag_28']].head(10))

df_model_1['lag_1'].fillna(0,inplace=True)
df_model_1['lag_7'].fillna(0,inplace=True)
df_model_1['lag_14'].fillna(0,inplace=True)
df_model_1['lag_28'].fillna(0,inplace=True)

df_model_1.head()
# df_model_1.drop_duplicates(keep='first',inplace=True)
df_model_1.shape

df_model_1['rolling_mean_7']=target.shift(1).rolling(7).mean()
df_model_1['rolling_mean_14']=target.shift(1).rolling(14).mean()
df_model_1['rolling_mean_28']=target.shift(1).rolling(28).mean()

df_model_1['rolling_std_7']=target.shift(1).rolling(1).std()
df_model_1['ewm_7']=target.shift(1).ewm(span=7, adjust=False).mean()

df_model_1.head()
df_model_1.fillna(0,inplace=True)
df_model_1.info()

x_train,x_test,y_train,y_test=train_test_split(df_model_1.drop(columns=['order_date','number_of_shipments']),df_model_1['number_of_shipments'],test_size=0.2,random_state=42,shuffle=True)

from xgboost import XGBRegressor

model = XGBRegressor(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=5,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

model.fit(x_train,y_train)

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score,accuracy_score
y_pred=model.predict(x_test)

print(r2_score(y_test,y_pred))

mean_absolute_error(y_test,y_pred)

mean_squared_error(y_test,y_pred)

y_pred

import pandas as pd
import numpy as np

def forecast_shipments(model, df_model_1, n_days):

    history = df_model_1.sort_values(
        'order_date'
        )

    forecasts = []
    recent_date=pd.Timestamp.today().normalize()
    start_date = recent_date - pd.Timedelta(days=30)
    history=history[(history['order_date']>=start_date) & (history['order_date']<=recent_date)]

    for i in range(n_days):


        next_date = (
            recent_date
            + pd.Timedelta(days=1)
        )


        month = next_date.month
        week_of_year = next_date.isocalendar().week
        quarter = next_date.quarter

        is_weekend = int(
            next_date.dayofweek >= 5
        )

        is_month_start = int(
            next_date.is_month_start
        )

        is_month_end = int(
            next_date.is_month_end
        )


        lag_1 = history.iloc[-1]['number_of_shipments']
        lag_7 = history.iloc[-7]['number_of_shipments']
        lag_14 = history.iloc[-14]['number_of_shipments']
        lag_28 = history.iloc[-28]['number_of_shipments']


        rolling_mean_7 = (
            history.tail(7)
            ['number_of_shipments']
            .mean()
        )

        rolling_mean_14 = (
            history.tail(14)
            ['number_of_shipments']
            .mean()
        )

        rolling_mean_28 = (
            history.tail(28)
            ['number_of_shipments']
            .mean()
        )

        rolling_std_7 = (
            history.tail(7)
            ['number_of_shipments']
            .std()
        )

        ewm_7 = (
            history['number_of_shipments']
            .ewm(
                span=7,
                adjust=False
            )
            .mean()
            .iloc[-1]
        )



        X_future = pd.DataFrame({
            'month': [month],
            'week_of_year': [week_of_year],
            'quarter': [quarter],
            'is_weekend': [is_weekend],
            'is_month_start': [is_month_start],
            'is_month_end': [is_month_end],
            'lag_1': [lag_1],
            'lag_7': [lag_7],
            'lag_14': [lag_14],
            'lag_28': [lag_28],
            'rolling_mean_7': [rolling_mean_7],
            'rolling_mean_14': [rolling_mean_14],
            'rolling_mean_28': [rolling_mean_28],
            'rolling_std_7': [rolling_std_7],
            'ewm_7': [ewm_7]
        })



        prediction = model.predict(
            X_future
        )[0]


        prediction = max(
            0,
            round(prediction)
        )


        forecasts.append({
            'forecast_date': next_date,
            'predicted_shipments': prediction
        })



        new_row = {
            'order_date': next_date,
            'month': month,
            'week_of_year': week_of_year,
            'quarter': quarter,
            'is_weekend': is_weekend,
            'is_month_start': is_month_start,
            'is_month_end': is_month_end,
            'number_of_shipments': prediction,
            'lag_1': lag_1,
            'lag_7': lag_7,
            'lag_14': lag_14,
            'lag_28': lag_28,
            'rolling_mean_7': rolling_mean_7,
            'rolling_mean_14': rolling_mean_14,
            'rolling_mean_28': rolling_mean_28,

            'rolling_std_7': rolling_std_7,

            'ewm_7': ewm_7
        }

        history = pd.concat(
            [
                history,
                pd.DataFrame([new_row])
            ],
            ignore_index=True
        )
        recent_date=next_date


    forecast_df = pd.DataFrame(
        forecasts
    )

    return forecast_df

forecast_shipments(model,df_model_1,5)



df_log['package_type'].value_counts()

# demand forecasting for weights



daily=df_log.groupby('order_date')
df_log['total_weight']=df_log['order_date'].apply(lambda x:daily.get_group(x)['package_weight_kg'].sum())

df_log.head()
df_log[df_log['order_date']==pd.to_datetime('2025-06-30')].head()

df_model_2=df_log[['order_date','total_weight','month','week_of_year','quarter','is_weekend','is_month_start','is_month_end']]
df_model_2.head()

df_model_2=df_model_2.sort_values('order_date').reset_index(drop=True)

df_model_1.head()

df_model_2.head()
df_model_2.drop_duplicates(keep='first',inplace=True)
df_model_2.shape

# Month number (1-12)
df_log['month'] = df_log['order_date'].dt.month

# Day of week (Monday=0, Sunday=6)
df_log['day_of_week'] = df_log['order_date'].dt.dayofweek

# Week of year (1-52/53)
df_log['week_of_year'] = df_log['order_date'].dt.isocalendar().week.astype(int)

# Quarter (1-4)
df_log['quarter'] = df_log['order_date'].dt.quarter

# Weekend or not (1 = Weekend, 0 = Weekday)
df_log['is_weekend'] = (
    df_log['order_date'].dt.dayofweek >= 5
).astype(int)

# Is first day of month
df_log['is_month_start'] = (
    df_log['order_date'].dt.is_month_start
).astype(int)

# Is last day of month
df_log['is_month_end'] = (
    df_log['order_date'].dt.is_month_end
).astype(int)

df_model_2

target_model_2=df_model_2['total_weight']

df_model_2['lag_1']  = target_model_2.shift(1)    # yesterday's count
df_model_2['lag_7']  = target_model_2.shift(7)    # same day last week
df_model_2['lag_14'] = target_model_2.shift(14)   # same day 2 weeks ago
df_model_2['lag_28'] = target_model_2.shift(28)   # same day 4 weeks ago

df_model_2['rolling_mean_7']=target_model_2.shift(1).rolling(7).mean()
df_model_2['rolling_mean_14']=target_model_2.shift(1).rolling(14).mean()
df_model_2['rolling_mean_28']=target_model_2.shift(1).rolling(28).mean()

df_model_2['rolling_std_7']=target_model_2.shift(1).rolling(1).std()
df_model_2['ewm_7']=target_model_2.shift(1).ewm(span=7, adjust=False).mean()

df_model_2.fillna(0,inplace=True)

df_model_2.head()

x_train,x_test,y_train,y_test=train_test_split(df_model_2.drop(columns=['order_date','total_weight']),df_model_2['total_weight'],test_size=0.2,random_state=42,shuffle=True)

from xgboost import XGBRegressor

model = XGBRegressor(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=5,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

model_2=model.fit(x_train,y_train)

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score,accuracy_score
y_pred=model_2.predict(x_test)

r2_score(y_test,y_pred)
mean_squared_error(y_test,y_pred)



y_pred

# predict weights

import pandas as pd
import numpy as np

def forecast_weight(model, df_model_2, n_days):
    history=df_model_2.sort_values('order_date')
    recent_date=pd.Timestamp.today().normalize()
    start_date = recent_date - pd.Timedelta(days=30)
    history=history[(history['order_date']>=start_date) & (history['order_date']<=recent_date)]

    forecasts = []

    for _ in range(n_days):

        next_date = (
            recent_date
            + pd.Timedelta(days=1)
        )



        month = next_date.month
        week_of_year = next_date.isocalendar().week
        quarter = next_date.quarter

        is_weekend = int(
            next_date.dayofweek >= 5
        )

        is_month_start = int(
            next_date.is_month_start
        )

        is_month_end = int(
            next_date.is_month_end
        )



        lag_1 = history.iloc[-1]['total_weight']
        lag_7 = history.iloc[-7]['total_weight']
        lag_14 = history.iloc[-14]['total_weight']
        lag_28 = history.iloc[-28]['total_weight']


        rolling_mean_7 = (
            history.tail(7)
            ['total_weight']
            .mean()
        )

        rolling_mean_14 = (
            history.tail(14)
            ['total_weight']
            .mean()
        )

        rolling_mean_28 = (
            history.tail(28)
            ['total_weight']
            .mean()
        )

        rolling_std_7 = (
            history.tail(7)
            ['total_weight']
            .std()
        )

        ewm_7 = (
            history['total_weight']
            .ewm(
                span=7,
                adjust=False
            )
            .mean()
            .iloc[-1]
        )



        X_future = pd.DataFrame({
            'month': [month],
            'week_of_year': [week_of_year],
            'quarter': [quarter],
            'is_weekend': [is_weekend],
            'is_month_start': [is_month_start],
            'is_month_end': [is_month_end],
            'lag_1': [lag_1],
            'lag_7': [lag_7],
            'lag_14': [lag_14],
            'lag_28': [lag_28],
            'rolling_mean_7': [rolling_mean_7],
            'rolling_mean_14': [rolling_mean_14],
            'rolling_mean_28': [rolling_mean_28],
            'rolling_std_7': [rolling_std_7],
            'ewm_7': [ewm_7]
        })



        prediction = model.predict(
            X_future
        )[0]

        prediction = max(
            0,
            prediction
        )



        forecasts.append({
            'forecast_date': next_date,
            'predicted_weight_kg': round(
                prediction,
                0
            )
        })



        new_row = {
            'order_date': next_date,
            'month': month,
            'week_of_year': week_of_year,
            'quarter': quarter,
            'is_weekend': is_weekend,
            'is_month_start': is_month_start,
            'is_month_end': is_month_end,
            'total_weight': prediction,
            'lag_1': lag_1,
            'lag_7': lag_7,
            'lag_14': lag_14,
            'lag_28': lag_28,
            'rolling_mean_7': rolling_mean_7,
            'rolling_mean_14': rolling_mean_14,
            'rolling_mean_28': rolling_mean_28,
            'rolling_std_7': rolling_std_7,
            'ewm_7': ewm_7
        }

        history = pd.concat(
            [
                history,
                pd.DataFrame([new_row])
            ],
            ignore_index=True
        )
        recent_date=next_date



    return pd.DataFrame(forecasts)

forecast_weight(model_2,df_model_2,30)

# scenario analysis
# what if demand increases by 12 percent

def scenario_demand(model_weight,forecast_weight,df_log,per,total_trucks,average_weight_cap):
  today = pd.Timestamp.today().normalize()
  month_start = today.replace(day=1)
  month_end = today + pd.offsets.MonthEnd(0)
  days_left=month_end.day-today.day
  print(days_left)
  total_pred_weight=0
  if days_left>0:
     df=forecast_weight(model_weight,df_log.copy(),days_left)
     total_pred_weight=df['predicted_weight_kg'].sum()

  df_log=df_log.sort_values('order_date').copy()
  df_log=df_log[(df_log['order_date']>=month_start) & (df_log['order_date']<=today)]

  total_prev_weight=df_log['total_weight'].sum()

  over_all_weight=(total_pred_weight+total_prev_weight)/30

  over_all_weight=over_all_weight+(over_all_weight*(per/100))

  if over_all_weight<=(average_weight_cap*total_trucks):
    print("0 trucks needed")

  else:
    extra_trucks=np.ceil((over_all_weight-(average_weight_cap*total_trucks))/average_weight_cap)
    print("extra trucks needed",extra_trucks)

scenario_demand(model_2,forecast_weight,df_model_2,12,20,100)

