# -*- coding: utf-8 -*-
"""ship_allocation_route

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ma95pJa5PYxHfZysgQepxGTuIsw9m1dW
"""

import numpy as np
import pandas as pd

def get_trucks():
    trucks = []

    num_trucks = int(input("Enter number of trucks: "))

    for _ in range(num_trucks):

        truck_id = input("\nEnter Truck ID: ")
        capacity = float(input("Enter truck capacity (kg): "))
        existing_orders = []

        has_existing = input(
            "Does this truck already have loaded orders? (y/n): "
        ).lower()

        if has_existing == "y":

            num_existing = int(
                input("How many existing orders are inside this truck? ")
            )

            for _ in range(num_existing):

                order_id = input("Existing Order ID: ")
                weight = float(input("Order Weight (kg): "))
                destination = input("Destination: ")

                existing_orders.append({
                    "order_id": order_id,
                    "weight": weight,
                    "destination": destination
                })

        trucks.append({
            "truck_id": truck_id,
            "capacity": capacity,
            "existing_orders": existing_orders
        })

    return trucks

"""### How to use `input()` in Colab

When a cell containing an `input()` function is executed, an input box will appear directly below that cell. Type your response into the box and press `Enter` to submit the input.
"""

truck_data = get_trucks()
print('\nCollected Truck Data:')
print(truck_data)

def get_orders():
    orders = []

    num_orders = int(input("\nEnter number of new orders: "))

    for _ in range(num_orders):

        order_id = input("\nEnter Order ID: ")
        weight = float(input("Enter order weight (kg): "))
        destination = input("Enter destination: ")

        orders.append({
            "order_id": order_id,
            "weight": weight,
            "destination": destination
        })

    return orders

order_data=get_orders()

print(order_data)

def allocate_orders(trucks, orders):

    # Calculate remaining capacity for every truck
    for truck in trucks:
        used_capacity = sum(
            order["weight"]
            for order in truck["existing_orders"]
        )

        truck["remaining_capacity"] = (
            truck["capacity"] - used_capacity
        )

        truck["assigned_orders"] = []

    # Heaviest orders allocated first
    orders = sorted(
        orders,
        key=lambda x: x["weight"],
        reverse=True
    )

    unallocated_orders = []

    # Allocate orders
    for order in orders:

        allocated = False

        for truck in trucks:

            if truck["remaining_capacity"] >= order["weight"]:

                truck["assigned_orders"].append(order)

                truck["remaining_capacity"] -= order["weight"]

                allocated = True
                break

        if not allocated:
            unallocated_orders.append(order)

    return trucks, unallocated_orders

orders=allocate_orders(truck_data,order_data)

print(orders)

city_coords = {
    'north': [
        ('Delhi', 28.6139, 77.2090),
        ('Lucknow', 26.8467, 80.9462),
        ('Jaipur', 26.9124, 75.7873),
        ('Chandigarh', 30.7333, 76.7794),
        ('Agra', 27.1767, 78.0081),
    ],
    'south': [
        ('Chennai', 13.0827, 80.2707),
        ('Bangalore', 12.9716, 77.5946),
        ('Hyderabad', 17.3850, 78.4867),
        ('Kochi', 9.9312, 76.2673),
        ('Coimbatore', 11.0168, 76.9558),
    ],
    'east': [
        ('Kolkata', 22.5726, 88.3639),
        ('Bhubaneswar', 20.2961, 85.8245),
        ('Patna', 25.5941, 85.1376),
        ('Guwahati', 26.1445, 91.7362),
        ('Ranchi', 23.3441, 85.3096),
    ],
    'west': [
        ('Mumbai', 19.0760, 72.8777),
        ('Pune', 18.5204, 73.8567),
        ('Ahmedabad', 23.0225, 72.5714),
        ('Surat', 21.1702, 72.8311),
        ('Nagpur', 21.1458, 79.0882),
    ],
    'central': [
        ('Bhopal', 23.2599, 77.4126),
        ('Indore', 22.7196, 75.8577),
        ('Jabalpur', 23.1815, 79.9864),
        ('Gwalior', 26.2183, 78.1828),
        ('Raipur', 21.2514, 81.6296),
    ],
}

from math import radians, sin, cos, sqrt, atan2

# Convert city_coords into a simple dictionary
city_locations = {}

for region in city_coords.values():
    for city, lat, lon in region:
        city_locations[city.lower()] = (lat, lon)

# Warehouse location
city_locations["kanpur"] = (26.4499, 80.3319)


def haversine(city1, city2):
    lat1, lon1 = city_locations[city1.lower()]
    lat2, lon2 = city_locations[city2.lower()]

    R = 6371  # Earth radius in km

    dlat = radians(lat2 - lat1)
    dlon = radians(lon2 - lon1)

    a = (
        sin(dlat / 2) ** 2
        + cos(radians(lat1))
        * cos(radians(lat2))
        * sin(dlon / 2) ** 2
    )

    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    return R * c


def optimize_routes(trucks, start_city="kanpur"):

    truck_routes = {}

    for truck in trucks:

        # Start from warehouse
        route = [start_city.title()]

        # Existing orders must be delivered first
        existing_destinations = [
            order["destination"].lower()
            for order in truck.get("existing_orders", [])
        ]

        route.extend([city.title() for city in existing_destinations])

        current_city = (
            existing_destinations[-1]
            if existing_destinations
            else start_city
        )

        # New assigned orders
        remaining_destinations = [
            order["destination"].lower()
            for order in truck.get("assigned_orders", [])
        ]

        # Find nearest destination repeatedly
        while remaining_destinations:

            nearest_city = min(
                remaining_destinations,
                key=lambda city:
                haversine(current_city, city)
            )

            route.append(nearest_city.title())

            remaining_destinations.remove(nearest_city)

            current_city = nearest_city

        # Return to warehouse
        route.append(start_city.title())

        truck_routes[truck["truck_id"]] = route

    return truck_routes

routes = optimize_routes(orders[0])

for truck_id, route in routes.items():
    print(f"\nTruck {truck_id}")
    print(" -> ".join(route))

!pip install folium

for truck_id, info in truck_routes.items():
    out_path = f"route_map_{truck_id}.html"
    plot_route_on_map(truck_id, info, save_path=out_path)
    print(f"Saved map: {out_path}")

truck_map = plot_route_on_map("T1", truck_routes["T1"])
truck_map  # just leave the Folium map object as the last line in a cell — it renders inline

